### ISSUE TITLE
the position of the type animation effect didn't right when I edit an existing file, while in a new buffer it works

### ISSUE THREAD

**Issue by xqin** [mattn/vim-particle#1]
the position of the type animation effect didn't right when I edit an existing file, while in a new buffer it works.

like this:
![e gif](https://cloud.githubusercontent.com/assets/1265888/11524179/59d3c2fa-9903-11e5-89c8-70f5c21fa06b.gif)

**Comment by mattn** [comment]
I can't read chinese.

**Comment by mattn** [comment]
vim-particles uses Vim scrip APIs screencol/screenrow. It is APIs that return current location of terminal. So if you use some plugins that modify statusline, it may break the location.

**Comment by xqin** [comment]
Thanks.
