### ISSUE TITLE
Vim-particle on linux

### ISSUE THREAD

**Issue by Franchium** [mattn/vim-particle#4]
How can i install this plugin on linux? Please reply

**Comment by mattn** [comment]
Please see README.

**Comment by Franchium** [comment]
I really dont understand, mingw32-make, what is it? I try install on linux using pacman -S mingw32-make and no pkg like that.

Also on the requirements said windows! Is that for windows os or what

**Comment by mattn** [comment]
This is duplicated issue https://github.com/mattn/vim-particle/issues/3

**Comment by Franchium** [comment]
I dont find any solution on that

**Comment by mattn** [comment]
Because this plugin works on Windows.

**Comment by Franchium** [comment]
Why there is no plugin particle on linux?

**Comment by mattn** [comment]
I don't know. Please find out (or create) it your self.
